services:
  - type: web
    name: campus-jobs-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: your-mongo-uri
      - key: JWT_SECRET
        value: your-jwt-secret

